-- Logs every inbound query (river name typed/texted) so we can see demand for
-- gauges that aren't covered yet, and how often lookups fail, over more than the
-- few days Cloudflare Workers Logs retains.
create table if not exists query_log (
  id         bigint generated by default as identity primary key,
  query      text not null,
  resolved   boolean not null,
  channel    text not null check (channel in ('inreach', 'email', 'none')),
  created_at timestamptz not null default now()
);

create index if not exists query_log_created_at_idx on query_log (created_at desc);
create index if not exists query_log_unresolved_idx on query_log (query) where not resolved;

alter table query_log enable row level security;

-- The Worker only holds the anon key, so it needs insert access. No select policy:
-- this isn't meant to be publicly queryable like `gauges` -- read it via the
-- Supabase dashboard/SQL editor with an authenticated role.
create policy "anon insert"
  on query_log for insert
  to anon
  with check (true);
