-- 008: 'canary' query channel + the watchdog's narrow read function.
--
-- The nightly GitHub-Actions email canary (scripts/email-canary.mjs) is logged
-- with channel 'canary' so it never pollutes real paddler telemetry. Migration
-- 007's CHECK would silently reject those rows (logQuery swallows errors by
-- design), so the constraint must be recreated first.
--
-- Apply manually: paste into the Supabase SQL editor (same convention as
-- 002_schedule.sql). If the DROP fails, the autogenerated constraint name
-- differs — find it with:
--   select conname from pg_constraint where conrelid = 'query_log'::regclass;

alter table query_log drop constraint if exists query_log_channel_check;
alter table query_log add constraint query_log_channel_check
  check (channel in ('inreach', 'email', 'none', 'canary'));

-- Watchdog read path (src/canarySweep.ts buildWatchdogCheck): the Worker holds
-- only the anon key and query_log is deliberately insert-only for anon (007).
-- This SECURITY DEFINER function exposes exactly ONE timestamp — when the
-- canary last ran — and no query text, so the anon grant leaks nothing.
create or replace function canary_last_seen()
returns timestamptz
language sql
security definer
set search_path = public
stable
as $$
  select max(created_at) from query_log where channel = 'canary';
$$;

revoke all on function canary_last_seen() from public;
grant execute on function canary_last_seen() to anon;
